import * as core from '@actions/core';
import { getOctokit, context } from '@actions/github';

interface Commit {
  sha: string;
  message: string;
  author: string;
  date: string;
}

interface ParsedCommit {
  type: string;
  scope: string;
  subject: string;
  raw: string;
}

const CONVENTIONAL_TYPES: Record<string, string> = {
  feat: 'Features',
  fix: 'Bug Fixes',
  docs: 'Documentation',
  style: 'Styles',
  refactor: 'Code Refactoring',
  perf: 'Performance Improvements',
  test: 'Tests',
  build: 'Build System',
  ci: 'CI/CD',
  chore: 'Maintenance',
  revert: 'Reverts'
};

const DEFAULT_SECTION_ORDER = [
  'Features',
  'Bug Fixes',
  'Performance Improvements',
  'Code Refactoring',
  'Documentation',
  'Styles',
  'Tests',
  'CI/CD',
  'Build System',
  'Maintenance',
  'Reverts'
];

function parseCommitMessage(message: string): ParsedCommit | null {
  const lines = message.split('\n');
  const firstLine = lines[0];

  // Match conventional commit format: type(scope): subject
  const match = firstLine.match(/^(\w+)(?:\(([^)]+)\))?:\s*(.+)$/);
  if (!match) {
    return null;
  }

  return {
    type: match[1],
    scope: match[2] || '',
    subject: match[3],
    raw: firstLine
  };
}

function categorizeCommit(parsed: ParsedCommit): string | null {
  const type = parsed.type.toLowerCase();
  return CONVENTIONAL_TYPES[type] || null;
}

function formatCommit(parsed: ParsedCommit): string {
  let line = `- ${parsed.subject}`;
  if (parsed.scope) {
    line += ` (${parsed.scope})`;
  }
  return line;
}

function formatUnconventional(commit: Commit): string {
  const sha = commit.sha.substring(0, 7);
  const firstLine = commit.message.split('\n')[0];
  return `- ${firstLine} - \`${sha}\``;
}

async function getCommits(
  octokit: ReturnType<typeof getOctokit>,
  owner: string,
  repo: string,
  baseRef: string,
  headRef: string
): Promise<Commit[]> {
  try {
    const { data } = await octokit.rest.repos.compareCommits({
      owner,
      repo,
      base: baseRef,
      head: headRef
    });

    return data.commits.map((c: { sha: string; commit: { message: string; author?: { name?: string; date?: string } | null } }) => ({
      sha: c.sha,
      message: c.commit.message,
      author: c.commit.author?.name || 'Unknown',
      date: c.commit.author?.date || new Date().toISOString()
    }));
  } catch (error: any) {
    core.warning(`Could not compare commits: ${error.message}`);
    return [];
  }
}

function generateReleaseNotes(
  sections: Map<string, ParsedCommit[]>,
  uncategorized: Commit[],
  template: string,
  includeUnlabelled: boolean
): string {
  let output = template || '';

  const defaultTemplate = `## 🚀 What's Changed\n\n{{changes}}\n\n---\n*Generated by Release Notes Drafter*`;

  if (!output) {
    output = defaultTemplate;
  }

  // Build changes section
  let changesHtml = '';

  for (const sectionName of DEFAULT_SECTION_ORDER) {
    const commits = sections.get(sectionName);
    if (commits && commits.length > 0) {
      changesHtml += `### ${sectionName}\n\n`;
      for (const parsed of commits) {
        changesHtml += formatCommit(parsed) + '\n';
      }
      changesHtml += '\n';
    }
  }

  if (includeUnlabelled && uncategorized.length > 0) {
    changesHtml += `### Other Changes\n\n`;
    for (const commit of uncategorized) {
      changesHtml += formatUnconventional(commit) + '\n';
    }
    changesHtml += '\n';
  }

  output = output.replace('{{changes}}', changesHtml);

  return output;
}

async function run(): Promise<void> {
  const token = core.getInput('token') || process.env.GITHUB_TOKEN;
  const baseRefInput = core.getInput('base-ref');
  const headRefInput = core.getInput('head-ref');
  const template = core.getInput('template');
  const includeUnlabelled = core.getInput('include-unlabelled') !== 'false';

  if (!token) {
    core.setFailed('GitHub token is required');
    return;
  }

  const octokit = getOctokit(token);
  const owner = context.repo.owner;
  const repo = context.repo.repo;

  // Determine base and head refs
  let baseRef = baseRefInput;
  let headRef = headRefInput;

  if (!baseRef) {
    // Try to get from payload
    baseRef = context.payload.base_ref || 'main';
  }

  if (!headRef) {
    headRef = context.payload.head_ref || context.ref.replace('refs/heads/', '');
  }

  core.info(`🔍 Comparing ${baseRef}...${headRef}`);

  const commits = await getCommits(octokit, owner, repo, baseRef, headRef);
  core.info(`📝 Found ${commits.length} commits`);

  const sections = new Map<string, ParsedCommit[]>();
  const uncategorized: Commit[] = [];
  let featureCount = 0;
  let fixCount = 0;
  let docsCount = 0;

  for (const commit of commits) {
    const parsed = parseCommitMessage(commit.message);

    if (parsed) {
      const section = categorizeCommit(parsed);
      if (section) {
        if (!sections.has(section)) {
          sections.set(section, []);
        }
        sections.get(section)!.push(parsed);

        // Count categories
        const type = parsed.type.toLowerCase();
        if (type === 'feat') featureCount++;
        if (type === 'fix') fixCount++;
        if (type === 'docs') docsCount++;
      } else if (includeUnlabelled) {
        uncategorized.push(commit);
      }
    } else if (includeUnlabelled) {
      uncategorized.push(commit);
    }
  }

  const releaseNotes = generateReleaseNotes(sections, uncategorized, template, includeUnlabelled);

  core.setOutput('release_notes', releaseNotes);
  core.setOutput('changed_features', featureCount.toString());
  core.setOutput('changed_fixes', fixCount.toString());
  core.setOutput('changed_docs', docsCount.toString());

  // Also set as summary for PR comment
  core.info('\n' + releaseNotes);
}

run();
